# Generated by Django 6.0 on 2026-04-03 07:44

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True)),
                ('estilo_musical', models.CharField(default='Salsa', max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='djs/')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título o Descripción')),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='archivo')),
                ('es_video', models.BooleanField(default=False, help_text='Marcar si el archivo subido es un video')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galería de Fotos y Videos',
                'verbose_name_plural': 'Galería de Fotos y Videos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField()),
                ('ciudad', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=200)),
                ('tipo_ritmo', models.CharField(default='Salsa', max_length=50)),
                ('precio_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('es_destacado', models.BooleanField(default=False)),
                ('imagen_portada', models.ImageField(upload_to='eventos/')),
                ('capacidad_maxima', models.PositiveIntegerField(default=100, help_text='Aforo total permitido')),
                ('artistas', models.ManyToManyField(related_name='eventos', to='eventos.dj')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(default='MercadoPago', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: General, VIP, Fase 1', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_disponible', models.PositiveIntegerField(default=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_tickets', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguridad', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('precio_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='eventos.orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.tipoticket')),
            ],
        ),
    ]
