# Generated by Django 6.0.1 on 2026-04-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriamedia',
            name='categoria',
            field=models.CharField(choices=[('evento', 'Fotos de Eventos'), ('promo', 'Promocionales'), ('dj', 'Artistas')], default='evento', max_length=20),
        ),
    ]
