# Generated by Django 6.0.1 on 2026-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_galeriamedia_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoticket',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='tipoticket',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Prioridad de venta (1 es primero)'),
        ),
    ]
