# Generated by Django 6.0 on 2026-04-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_tipoticket_options_tipoticket_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_validate_tickets', 'Puede validar tickets en la puerta')]},
        ),
    ]
